/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 * vim: set sw=4 ts=4 et: */
/* ***** BEGIN LICENSE BLOCK *****
 *  Version: GPL 3
 * 
 *  This program is Copyright (C) 2007-2008 Aptana, Inc. All Rights Reserved
 *  This program is licensed under the GNU General Public license, version 3 (GPL).
 * 
 *  This program is distributed in the hope that it will be useful, but
 *  AS-IS and WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, TITLE, or
 *  NONINFRINGEMENT. Redistribution, except as permitted by the GPL,
 *  is prohibited.
 * 
 *  You can redistribute and/or modify this program under the terms of the GPL, 
 *  as published by the Free Software Foundation.  You should
 *  have received a copy of the GNU General Public License, Version 3 along
 *  with this program; if not, write to the Free Software Foundation, Inc., 51
 *  Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *  
 *  Aptana provides a special exception to allow redistribution of this file
 *  with certain other code and certain additional terms
 *  pursuant to Section 7 of the GPL. You may view the exception and these
 *  terms on the web at http://www.aptana.com/legal/gpl/.
 *  
 *  You may view the GPL, and Aptana's exception and additional terms in the file
 *  titled license-jaxer.html in the main distribution folder of this program.
 *  
 *  Any modifications to this file must keep this entire header intact.
 * 
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"

interface jxIMySQL50ResultSet;
interface jxIMySQL50Statement;

[ptr] native jxMYSQLPtr(st_mysql);
[ptr] native jxMYSQLSTMTPtr(st_mysql_stmt);


%{C++
struct st_mysql;
struct st_mysql_stmt;

%}


[scriptable, uuid(850de0fa-0597-4aa5-bf60-05fbeb665e32)]
interface jxIMySQL50 : nsISupports
{
    /**
     *  Accessor to the MYSQL structure this MySQL50 connection is associated with.      
     */
	[noscript] readonly attribute jxMYSQLPtr mysql;

    /**
     *  Accessor to the host name this MySQL50 connection is associated with.      
     */
    attribute AString host;

    /**
     *  Accessor to the user name this MySQL50 connection is associated with.      
     */
    attribute AString user;

    /**
     *  Accessor to the pswd this MySQL50 connection is associated with.      
     */
    attribute AString password;

    /**
     *  Accessor to the database name this MySQL50 connection is associated with.      
     */
    attribute AString database;

    /**
     *  Accessor to the port number this MySQL50 connection is associated with.      
     */
    attribute unsigned long port;

    /**
     *  Accessor to the socket this MySQL50 connection is associated with.      
     */
    attribute AString socket;

    /**
     *  Accessor to the options this MySQL50 connection is associated with.      
     */
    readonly attribute unsigned long options;

    /**
     *  Accessor to the indicator describing whether this MySQL50 object is connected to a DB or not.
     */
    [noscript] readonly attribute boolean connected;

    /**
     *  Accessor to the characterSet name this MySQL50 connection is associated with.      
     */
    readonly attribute AString characterSet;



    /**
     *  Accessors for the connection options.
     */
	readonly attribute unsigned long CLIENT_COMPRESS;
	readonly attribute unsigned long CLIENT_FOUND_ROWS;
	readonly attribute unsigned long CLIENT_IGNORE_SPACE;
	readonly attribute unsigned long CLIENT_INTERACTIVE;
	readonly attribute unsigned long CLIENT_LOCAL_FILES;
	readonly attribute unsigned long CLIENT_MULTI_RESULTS;
	readonly attribute unsigned long CLIENT_MULTI_STATEMENTS;
	readonly attribute unsigned long CLIENT_NO_SCHEMA;
	readonly attribute unsigned long CLIENT_ODBC;
	readonly attribute unsigned long CLIENT_SSL;

    /**
     *  Accessors for the option() options.
     */
	readonly attribute unsigned long OPT_CONNECT_TIMEOUT		;
	readonly attribute unsigned long OPT_COMPRESS				;
	readonly attribute unsigned long OPT_NAMED_PIPE				;
	readonly attribute unsigned long INIT_COMMAND				;
	readonly attribute unsigned long READ_DEFAULT_FILE			;
	readonly attribute unsigned long READ_DEFAULT_GROUP			;
	readonly attribute unsigned long SET_CHARSET_DIR			;
	readonly attribute unsigned long SET_CHARSET_NAME			;
	readonly attribute unsigned long OPT_LOCAL_INFILE			;
	readonly attribute unsigned long OPT_PROTOCOL				;
	readonly attribute unsigned long SHARED_MEMORY_BASE_NAME	;
	readonly attribute unsigned long OPT_READ_TIMEOUT			;
	readonly attribute unsigned long OPT_WRITE_TIMEOUT			;
	readonly attribute unsigned long OPT_USE_RESULT				;
	readonly attribute unsigned long OPT_USE_REMOTE_CONNECTION	;
	readonly attribute unsigned long OPT_USE_EMBEDDED_CONNECTION;
	readonly attribute unsigned long OPT_GUESS_CONNECTION		;
	readonly attribute unsigned long SET_CLIENT_IP				;
	readonly attribute unsigned long SECURE_AUTH				;
	readonly attribute unsigned long REPORT_DATA_TRUNCATION		;
	readonly attribute unsigned long OPT_RECONNECT				;
	readonly attribute unsigned long OPT_SSL_VERIFY_SERVER_CERT ;




    /*************************************************************
     *  autocommit
     *
	 *  Sets autocommit mode on if mode is 1, off if mode is 0.  
     */
    boolean autocommit(in boolean mode);



    /*************************************************************
     *  changeUser
     *
 	 *	Changes the user and causes the database specified by db 
 	 *	to become the default (current) database on the connection.
 	 *	In subsequent queries, this database is the default for 
 	 *	table references that do not include an explicit database 
 	 *	specifier.
	 *
	 *	changeUser() fails if the connected user cannot be 
	 *	authenticated or doesn't have permission to use the 
	 *	database. In this case, the user and database are not changed.
	 *
	 *	The db parameter may be omitted if you don't want to 
	 *	have a default database.      
	 */
    boolean changeUser(in AString user, in AString password, in AString dbname);



    /*************************************************************
     *  clientInfo
     *
     *  Returns a string that represents the client library version.
     */
    AString clientInfo();

    /*************************************************************
     *  clientVersion
     *
	 *	Returns an integer that represents the client library version. 
	 *	The value has the format XYYZZ where X is the major version, 
	 *	YY is the release level, and ZZ is the version number within 
	 *	the release level. For example, a value of 40102 represents 
	 *	a client library version of 4.1.2.     
	 */
    unsigned long clientVersion();



    /*************************************************************
     *  close
     *
	 *  Closes this connection.  
     */
    void close();



    /*************************************************************
     *  commit
     *
	 *  Commits the current transaction.  
     */
    boolean commit();



    /*************************************************************
     *  escape
     *
	 *  Commits the current transaction.  
     */
    AString escape(in AString input);



    /*************************************************************
     *  info
     *
	 *	Retrieves a string providing information about the most recently 
	 *	executed statement, but only for the statements listed here. 
	 *	For other statements, info() returns an empty string. 
	 *	The format of the string varies depending on the type of statement, 
	 *	as described here. The numbers are illustrative only; the string 
	 *	contains values appropriate for the statement. 
	 *
	 *    * INSERT INTO ... SELECT ...
	 *		String format: Records: 100 Duplicates: 0 Warnings: 0
     *
	 *	  * INSERT INTO ... VALUES (...),(...),(...)...
	 *		String format: Records: 3 Duplicates: 0 Warnings: 0
     *
	 *	  * LOAD DATA INFILE ...
	 *		String format: Records: 1 Deleted: 0 Skipped: 0 Warnings: 0
     *
	 *	  * ALTER TABLE
	 *		String format: Records: 3 Duplicates: 0 Warnings: 0
     *
	 *	  * UPDATE
	 *		String format: Rows matched: 40 Changed: 40 Warnings: 0
	 *
	 *	Note that info() returns a non-empty value for 
	 *	INSERT ... VALUES only for the multiple-row form of the 
	 *	statement (that is, only if multiple value lists are specified).     
	 */
    AString info();



    /*************************************************************
     *  insertID
     *
	 */
    unsigned long long insertID();



    /*************************************************************
     *  rollback
     *
	 *  Rolls back the current transaction.  
     */
    boolean rollback();



    /*************************************************************
     *  hostInfo
     *
	 *  Returns a string describing the type of connection in use, 
	 *	including the server hostname.  
     */
    AString hostInfo();



    /*************************************************************
     *  nextResult
     *
     */
    jxIMySQL50ResultSet nextResult();



    /*************************************************************
     *  ping
     *
	 *	Checks whether the connection to the server is working. 
	 *	If the connection has gone down, an automatic reconnection 
	 *	is attempted.
	 *
	 *	This function can be used by clients that remain idle for 
	 *	a long while, to check whether the server has closed the 
	 *	connection and reconnect if necessary.
	 *
	 *
	 *	Return Value:
	 *
	 *	Zero if the connection to the server is alive. 
	 *	Non-zero if an error occurred. 
	 *	A non-zero return does not indicate whether the MySQL server 
	 *	itself is down; the connection might be broken for other 
	 *	reasons such as network problems.
	 *
	 *	Errors
	 *
	 *	CR_COMMANDS_OUT_OF_SYNC
	 *		Commands were executed in an improper order.
	 *
	 *	CR_SERVER_GONE_ERROR
	 *		The MySQL server has gone away.
	 *
	 *	CR_UNKNOWN_ERROR
	 *		An unknown error occurred.
     */
    long ping();



    /*************************************************************
     *  protocolVersion
     *
	 */
    unsigned long protocolVersion();



    /*************************************************************
     *  warningCount
     *
	 */
    unsigned long warningCount();



    /*************************************************************
     *  serverInfo
     *
	 *  Returns a string that represents the server version number.  
     */
    AString serverInfo();



    /*************************************************************
     *  SQLState
     *
     */
    AString SQLState();



    /*************************************************************
     *  serverVersion
     *
	 *  Returns the version number of the server as an integer.  
	 *
	 *
	 *	Return Value:
	 *
	 *	A number that represents the MySQL server version in this format:
	 *	major_version*10000 + minor_version *100 + sub_version
	 *
	 *	For example, 5.0.12 is returned as 50012.
	 *
	 *	This function is useful in client programs for quickly 
	 *	determining whether some version-specific server capability exists. 
     */
    unsigned long serverVersion();



    /*************************************************************
     *  stat
     *
	 *	Returns a character string containing information similar 
	 *	to that provided by the mysqladmin status  command. This 
	 *	includes uptime in seconds and the number of running threads, 
	 *	questions, reloads, and open tables.     
	 */
    AString stat();



    /*************************************************************
     *  threadSafe
     *
     */
    boolean threadSafe();



    /*************************************************************
     *  errno
     *
     *  Accessor to the error code for the most recently invoked API function that 
     *	can succeed or fail. A return value of zero means that no error occurred.
     */
    unsigned long errno();



    /*************************************************************
     *  error
     *
     *  Accessor to the error code for the most recently invoked API function that 
     *	can succeed or fail. A return value of zero means that no error occurred.
     */
    AString error();



    /*************************************************************
     *  option
	 *
	 *	Sets extra connect option and affect behavior for a connection. 
	 *	This function may be called multiple times to set several options.
	 *
	 *	option() should be called before connect().
	 *
     *
     *   @param option
	 *		 The option that you want to set.
     *
     *   @param arg
	 *		 The (optional) value for the option. 
     */
    long option(in unsigned long option);
    long optionString(in unsigned long option, in AString arg);
    long optionInt(in unsigned long option, in unsigned long arg);
    long optionBool(in unsigned long option, in boolean arg);


    /**
     *  Set the errno for the last error
     */
    [noscript] void setErrorNumber(in  unsigned long err);
    [noscript] void saveMySQLError();


    

    /*************************************************************
     *  connect
	 *
 	 *	Attempts to establish a connection to a MySQL database engine 
 	 *	running on host.  connect()  must complete successfully before 
 	 *	you can execute any other API functions that require a valid 
 	 *	connection.
     *
     *   @param host
     *		 The value of host may be either a hostname or an IP address. 
     *		 If host is the empty string or the string "localhost", a connection 
     *		 to the local host is assumed. For Windows, the client connects using 
     *		 a shared-memory connection, if the server has shared-memory connections 
     *		 enabled. Otherwise, TCP/IP is used. For Unix, the client connects using 
     *		 a Unix socket file. For local connections, you can also influence the 
     *		 type of connection to use with the MYSQL_OPT_PROTOCOL or MYSQL_OPT_NAMED_PIPE 
     *		 options to options().  The type of connection must be supported by the server. 
     *		 For a host value of "." on Windows, the client connects using a named pipe, 
     *		 if the server has named-pipe connections enabled. If named-pipe connections 
     *		 are not enabled, an error occurs.
     *
     *   @param user
     *		 The user parameter contains the user's MySQL login ID. If user is the empty 
     *		 string "", the current user is assumed. Under Unix, this is the current login 
     *		 name. Under Windows ODBC, the current username must be specified explicitly. 
     *
     *   @param password
     *		 The password parameter contains the password for user. If passwd is NULL, 
     *		 only entries in the user table for the user that have a blank (empty) password 
     *		 field are checked for a match. This allows the database administrator to set 
     *		 up the MySQL privilege system in such a way that users get different privileges 
     *		 depending on whether they have specified a password.
     *		 Note: Do not attempt to encrypt the password before calling connect(); password 
     *		 encryption is handled automatically by the client API.
     *
     *   @param dbname
     *		 The database name. If not NULL, the connection sets the default database to this value. 
     *
     *   @param port
	 *		 If port is not 0, the value is used as the port number for the TCP/IP 
	 *		 connection. 
     *
     *   @socket
     *       If socket is not NULL, the string specifies the socket or named pipe that should be used.
     *       Note that the host parameter determines the type of the connection.
     *
     *   @param options
	 *		 Usually 0, but can be set to a combination of flags to enable certain features.
     */
    boolean connect(in AString host, in AString user, in AString password, in AString dbname, in unsigned long port, in AString socket, in unsigned long options);


    /*************************************************************
     *  query
	 *
	 *	Executes a SQL statement.
 	 *
     *   @param statement
	 *		A single SQL statement and you should not add a terminating semicolon (‘;’) 
	 *		or \g to the statement. If multiple-statement execution has been enabled, 
	 *		the string can contain several statements separated by semicolons.     
	 */
    jxIMySQL50ResultSet query(in AString statement);


    /*************************************************************
     *  listFields
	 *
	 *	Returns a result set consisting of field names in the given 
	 *	table that match the simple regular expression specified by 
	 *	the wild parameter. wild may contain the wildcard characters 
	 *	‘%’ or ‘_’, or may be a NULL pointer to match all fields. 
	 *
	 *	Calling mysql_list_fields() is similar to executing the query 
	 *	SHOW COLUMNS FROM tbl_name [LIKE wild]. 	 
	 *
	 */
    jxIMySQL50ResultSet listFields(in AString table, in AString wild);


    /*************************************************************
     *  prepare
	 *
	 *	prepare a SQL statement.
 	 *
     *   @param statement
	 *		A single SQL statement and you should not add a terminating semicolon (‘;’) 
	 *		or \g to the statement. If multiple-statement execution has been enabled, 
	 *		the string can contain several statements separated by semicolons.     
	 */
    jxIMySQL50Statement prepare(in AString queryStr);
};

