top_srcdir   = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6
top_builddir = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6
srcdir       = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/echo
builddir     = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/echo
VPATH        = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/echo

include $(top_srcdir)/build/special.mk

