top_srcdir   = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6
top_builddir = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6
srcdir       = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/server/mpm
builddir     = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/server/mpm
VPATH        = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
