top_srcdir   = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6
top_builddir = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6
srcdir       = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/loggers
builddir     = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/loggers
VPATH        = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/loggers

include $(top_srcdir)/build/special.mk

