top_srcdir   = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6
top_builddir = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6
srcdir       = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/dav/fs
builddir     = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/dav/fs
VPATH        = /Users/paul/Documents/Jaxer-dev/httpd-2.2.6/modules/dav/fs
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
